### ISSUE TITLE
Add face detection layer

### ISSUE THREAD

**Issue by joseph-d-p** [joseph-d-p/gaze-estimation#1]
Using [face-detection-adas-binary-0001](https://docs.openvinotoolkit.org/latest/omz_models_intel_face_detection_adas_binary_0001_description_face_detection_adas_binary_0001.html#inputs) model to draw face bounding box and crop face region for next inference layer.

#### Input
```
Name: input, shape: [1x3x384x672] - An input image in the format [BxCxHxW],

where:
B - batch size
C - number of channels
H - image height
W - image width

Expected color order is BGR.
```

#### Output
- Face bounding box region shown in video
- Cropped face input for the next inference layer

#### Tasks
- [x] Pre-process input frame / image to input size expected by the model
- [x] Draw bounding box based on inference result
- [x] Return cropped face coordinates
