### ISSUE TITLE
Add feature landmarks detection routine

### ISSUE THREAD

**Issue by joseph-d-p** [joseph-d-p/gaze-estimation#2]
Using [landmarks-regression-retail-0009](https://docs.openvinotoolkit.org/latest/omz_models_intel_landmarks_regression_retail_0009_description_landmarks_regression_retail_0009.html) model to detect face landmarks: two eyes, nose, two lip corners.

#### Input

```
Name: "data" , shape: [1x3x48x48] - An input image in the format [BxCxHxW],

where:
B - batch size
C - number of channels
H - image height
W - image width

The expected color order is BGR.
```

#### Output
- Cropped left and right eye

#### Tasks
- [ ] Pre-process cropped face to input size expected by the model
- [ ] Draw bounding box for the two eyes
- [ ] Return coordinates of the two eyes
