### ISSUE TITLE
Benchmark layers

### ISSUE THREAD

**Issue by joseph-d-p** [joseph-d-p/gaze-estimation#7]
Benchmark performance of different layers

#### Tasks
- [ ] Benchmark face detection layer
- [ ] Benchmark feature landmarks detection layer
- [ ] Benchmark head pose estimation layer
- [ ] Benchmark gaze estimation layer
- [ ] Update documentation
